#!/usr/bin/env bash
if [ $1 == "-v" ]; then
	set -ex
else
	set -e
fi
#Script to Copy a Firefox Profile from a NFS userhome to a local disk
#Designed for osx but with aditional coding can be ported to other *nix Systems

RSYNC="/usr/bin/rsync"
LOCALPROFILEROOT="/Users/Shared/FirefoxProfiles"
NFSPROFILEROOT="${HOME}/Library/Application Support/Firefox/Profiles"
PROFILENAME="${LOGNAME}-local"
TMPFILE="/tmp/firefox-profile.isLoggedin"
RSYNCOPTIONS="-a --delete --exclude=cache2 --exclude=Cache --exclude=lock"
if [ $1 == "-v" ]; then
	RSYNCOPTIONS="-v $RSYNCOPTIONS"
fi

if [ ! -d ${LOCALPROFILEROOT} ]; then
	mkdir ${LOCALPROFILEROOT}
fi

onLogin() {
	if [ -d "${NFSPROFILEROOT}/${PROFILENAME}" ]; then
		${RSYNC} ${RSYNCOPTIONS} "${NFSPROFILEROOT}/${PROFILENAME}" "${LOCALPROFILEROOT}"
	fi
}

onLogout() {
	if [ -d "${LOCALPROFILEROOT}/${PROFILENAME}" ]; then
		${RSYNC} ${RSYNCOPTIONS} "${LOCALPROFILEROOT}/${PROFILENAME}" "${NFSPROFILEROOT}"
	fi
}

if [ -f ${TMPFILE} ]; then
	onLogout
	rm ${TMPFILE}
else
	onLogin
	touch ${TMPFILE}
fi
